bubolo: bubolo.world.entity.Actor Class Reference
bubolo.world.entity.Actor Class Reference abstract
Public Member Functions
Actor ()
Actor (UUID id)
Actor setHP (int i)
int getHP ()
int getMaxHP ()
Actor modifyHP (int i)
boolean isAlive ()
void destroy ()
Entity setParams (float x, float y, int w, int h, float rot)
UUID getId ()
void setId (UUID id)
int getHeight ()
int getWidth ()
void update ()
float getRotation ()
float getX ()
float getY ()
Entity setRotation (float newRotation)
Entity setX (float x)
Entity setY (float y)
Entity setWidth (int size)
Entity setHeight (int size)
Detailed Description
Basic class representing MobileEntities that exhibit some kind of behavior in the game world, such as tanks and humans.
Author
BU CS673 - Clone Productions
Definition at line 13 of file Actor.java.
Constructor & Destructor Documentation
bubolo.world.entity.Actor.Actor ()
Construct a new Actor with a random UUID.
Definition at line 24 of file Actor.java.
bubolo.world.entity.Actor.Actor (UUID id)
Construct a new Actor with the specified UUID.
Parameters
id is the existing UUID to be applied to the new Actor.
Definition at line 35 of file Actor.java.
Member Function Documentation
void bubolo.world.entity.Actor.destroy ()
Destroy this Damageable and clean up any remaining assets.
Implements bubolo.world.Damageable.
Definition at line 77 of file Actor.java.
int bubolo.world.entity.Entity.getHeight () inherited
Get the height of this Entity.
Returns
the height of this Entity in world coordinates.
Implements bubolo.graphics.Drawable.
Definition at line 88 of file Entity.java.
int bubolo.world.entity.Actor.getHP ()
Get the current HP value for this Damageable.
Returns
an int representing the current HP value.
Implements bubolo.world.Damageable.
Definition at line 49 of file Actor.java.
UUID bubolo.world.entity.Entity.getId () inherited
The Entity's unique id.
Returns
the Entity's unique id.
Definition at line 73 of file Entity.java.
int bubolo.world.entity.Actor.getMaxHP ()
Get the max HP value for this Damageable.
Returns
an int representing the maximum HP value.
Implements bubolo.world.Damageable.
Definition at line 56 of file Actor.java.
float bubolo.world.entity.Entity.getRotation () inherited
Get the current rotation of this Entity.
Returns
the rotation of this Entity in radians.
Implements bubolo.graphics.Drawable.
Definition at line 110 of file Entity.java.
int bubolo.world.entity.Entity.getWidth () inherited
Get the width of this Entity.
Returns
the height of this Entity in world coordinates.
Implements bubolo.graphics.Drawable.
Definition at line 94 of file Entity.java.
float bubolo.world.entity.Entity.getX () inherited
Get the x position of this Entity.
Returns
the entity's x position in world coordinates.
Implements bubolo.graphics.Drawable.
Definition at line 116 of file Entity.java.
float bubolo.world.entity.Entity.getY () inherited
Get the y position of this Entity.
Returns
the entity's y position in world coordinates.
Implements bubolo.graphics.Drawable.
Definition at line 122 of file Entity.java.
boolean bubolo.world.entity.Actor.isAlive ()
Test to see whether this Damageable should be considered 'alive' for the purposes of entity interactions.
Returns
true if the Damageable should be considered 'alive'.
Implements bubolo.world.Damageable.
Definition at line 70 of file Actor.java.
Actor bubolo.world.entity.Actor.modifyHP (int i)
Modify this Damageable's HP by the specified amount. Positive values should increase the current HP, negative values should decrease it.
Parameters
i is the amount to modify this Damageable's health by. Positive values increase HP, negative values decrease.
Returns
a reference to this Damageable.
Implements bubolo.world.Damageable.
Definition at line 63 of file Actor.java.
Entity bubolo.world.entity.Entity.setHeight (int size) inherited
Set this Entity's height.
Parameters
size is the desired Entity height in world coordinates.
Returns
this Entity.
Definition at line 187 of file Entity.java.
Referenced by bubolo.world.entity.Entity.setParams().
Actor bubolo.world.entity.Actor.setHP (int i)
Set the HP value f or this Damageable to the specified value.
Parameters
i is the value to set this Damageable's HP to.
Returns
a reference to this Damageable.
Implements bubolo.world.Damageable.
Definition at line 42 of file Actor.java.
void bubolo.world.entity.Entity.setId (UUID id) inherited
Sets the Entity's unique id.
Parameters
id the Entity's unique id.
Definition at line 82 of file Entity.java.
Entity bubolo.world.entity.Entity.setParams (float x, float y, int w, int h, float rot) inherited
Set the basic parameters for an Entity. Intended to be used after construction.
Parameters
x is the initial x position in world coordinates.
y is the initial y position in world coordinates.
w is the initial width in world coordinates.
h is the initial height in world coordinates.
rot is the initial rotation in radians.
Returns
a reference to this Entity.
Definition at line 59 of file Entity.java.
References bubolo.world.entity.Entity.setHeight(), bubolo.world.entity.Entity.setRotation(), bubolo.world.entity.Entity.setWidth(), bubolo.world.entity.Entity.setX(), and bubolo.world.entity.Entity.setY().
Entity bubolo.world.entity.Entity.setRotation (float newRotation) inherited
Set the rotation of this Entity.
Parameters
newRotation is the desired rotation state of this Entity in radians.
Returns
this Entity, after the rotation action has been completed.
Definition at line 134 of file Entity.java.
Referenced by bubolo.world.entity.Entity.setParams().
Entity bubolo.world.entity.Entity.setWidth (int size) inherited
Set this Entity's width.
Parameters
size is the desired Entity width in world coordinates.
Returns
this Entity.
Definition at line 174 of file Entity.java.
Referenced by bubolo.world.entity.Entity.setParams().
Entity bubolo.world.entity.Entity.setX (float x) inherited
Sets this Entity's x position.
Parameters
x is the desired x position in world coordinates.
Returns
this Entity.
Definition at line 148 of file Entity.java.
Referenced by bubolo.world.entity.Entity.setParams().
Entity bubolo.world.entity.Entity.setY (float y) inherited
Set this Entity's y position.
Parameters
y is the desired y position in world coordinates.
Returns
this Entity.
Definition at line 161 of file Entity.java.
Referenced by bubolo.world.entity.Entity.setParams().
void bubolo.world.entity.Entity.update () inherited
Updates the state of this Entity. Called multiple times per second to maintain current Entity state.
Definition at line 104 of file Entity.java.